### ISSUE TITLE
Error after update 1.0.1

### ISSUE THREAD

**Issue by matori** [textlint-ja/textlint-rule-no-insert-re#13]
Since updating to 1.0.1, getting the following error:

```
 TypeError: (0 , _kuromojin.default) is not a function
```

It seems that `npm test` also failing.

**Comment by shirayu** [comment]
Thank you for the report.
I fixed it at dc9c1af4b308edac24981e8711757d2a5113e412 and version 1.0.2.
